### ISSUE TITLE
Support for authenticated repos

### ISSUE THREAD

**Issue by iscChris** [gjsjohnmurray/iris-package-manager#1]
This is a fantastic tool but I didn't see a way to allow it to authenticate to the pm.intersystems.com repo which is based on token exchange.   Is this use case supported?

**Comment by iscChris** [comment]
No worries, just very excited about this tool.  It's fantastic!

**Comment by gjsjohnmurray** [comment]
Please tell your colleagues and encourage them to vote for it 👍
