### ISSUE TITLE
Add support for docker environment

### ISSUE THREAD

**Issue by evshvarov** [gjsjohnmurray/iris-package-manager#2]
Currently is not working:
<img width="598" alt="Screenshot 2024-09-28 at 11 14 19 AM" src="https://github.com/user-attachments/assets/f05830d9-4649-4c4f-97fe-bab72158f7a1">

**Comment by evshvarov** [comment]
Tried with this docker template:
https://openexchange.intersystems.com/package/objectscript-docker-template

**Comment by gjsjohnmurray** [comment]
Currently it requires a server definition in the Servers section. Please create yourself one pointing to port 49303 at local host using http.

**Comment by gjsjohnmurray** [comment]
@evshvarov after updating the extension to 1.0.4 you can now launch IPM in VS Code directly from the ObjectScript Explorer. So it's no longer necessary to define a Server Manager entry as I previously suggested.
